create table if not exists public.tracked_traders (
  id bigint generated by default as identity primary key,
  trader_name text not null,
  hypurrscan_url text not null,
  wallet_address text not null unique,
  is_active boolean not null default true,
  imported_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.signal_snapshots (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('running', 'success', 'partial', 'failed')),
  total_traders integer not null default 0,
  traders_completed integer not null default 0,
  traders_failed integer not null default 0,
  total_positions integer not null default 0,
  error_message text,
  created_at timestamptz not null default timezone('utc', now()),
  finished_at timestamptz
);

create table if not exists public.signal_trader_runs (
  id bigint generated by default as identity primary key,
  snapshot_id bigint not null references public.signal_snapshots(id) on delete cascade,
  trader_name text not null,
  wallet_address text not null,
  source_url text not null,
  status text not null check (status in ('running', 'success', 'failed')),
  positions_found integer not null default 0,
  error_message text,
  started_at timestamptz not null,
  finished_at timestamptz
);

create table if not exists public.trader_positions (
  id bigint generated by default as identity primary key,
  snapshot_id bigint not null references public.signal_snapshots(id) on delete cascade,
  trader_name text not null,
  wallet_address text not null,
  source_url text not null,
  token text not null,
  side text not null check (side in ('long', 'short')),
  value_usd numeric(20, 2) not null,
  market_type text not null check (market_type in ('crypto', 'tradfi')),
  scraped_at timestamptz not null,
  parse_status text not null default 'parsed'
);

create table if not exists public.token_signal_metrics (
  id bigint generated by default as identity primary key,
  snapshot_id bigint not null references public.signal_snapshots(id) on delete cascade,
  market_type text not null check (market_type in ('crypto', 'tradfi')),
  token text not null,
  smw_flows integer not null,
  holdings_usd numeric(20, 2) not null,
  long_smw integer not null,
  short_smw integer not null,
  long_value_usd numeric(20, 2) not null,
  short_value_usd numeric(20, 2) not null,
  unique (snapshot_id, market_type, token)
);

create index if not exists idx_signal_snapshots_created_at
  on public.signal_snapshots (created_at desc, id desc);

create index if not exists idx_signal_trader_runs_snapshot
  on public.signal_trader_runs (snapshot_id, id asc);

create index if not exists idx_trader_positions_snapshot_market_token
  on public.trader_positions (snapshot_id, market_type, token);

create index if not exists idx_token_signal_metrics_snapshot_market
  on public.token_signal_metrics (snapshot_id, market_type, smw_flows desc, holdings_usd desc, token asc);
